# Generated by Django 5.0.1 on 2024-07-08 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('purpose_of_visit', models.TextField(blank=True, null=True)),
                ('uploaded_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='app1.uploadedimage')),
            ],
        ),
    ]
