# Generated by Django 5.0.1 on 2024-07-08 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_visitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
