# Generated by Django 5.0.1 on 2024-10-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_attendance_check_in_time_attendance_check_out_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True)),
                ('camera_type', models.CharField(choices=[('USB', 'USB Camera'), ('IP', 'IP Camera')], default='USB', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
